max_steps = 500
batch_size = 1024
micro_batch_size = 1
seq_len = 2048
rollouts_per_prompt = 16
mask_truncated_completions = false

[model]
name = "Qwen/Qwen2.5-3B-Instruct"

[monitor.wandb]
project = "celeste-0000"

[monitor.wandb.log_extras]
samples = true
distributions = true
interval = 2

[environment]
id = "vf-celeste-0000"

[sampling]
max_tokens = 512

[ckpt]
interval = 100