max_steps = 500

[monitor.wandb]
project = "celeste-0001"

[model]
name = "Qwen/Qwen2.5-7B-Instruct"
liger_kernel = true

[model.lora]
enabled = true
rank = 32
alpha = 64.0
dropout = 0.05
target_modules = [
   ".*\\.q_proj$",
   ".*\\.k_proj$", 
   ".*\\.v_proj$",
   ".*\\.o_proj$",
]
trainable_modules = [
   "lm_head$",
   ".*\\.embed_tokens$",
   ".*\\.norm$",
]
merge_on_save = true
[model.ac]
freq = 1

[optim]
lr = 2e-4
max_norm = 0.02
weight_decay = 0.001

[ckpt]
interval = 100