[project]
name = "vf-celeste-0001"
version = "0.1.0"
dependencies = [
    "scikit-learn>=1.7.1",
    "verifiers>=0.1.2.post0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["vf_celeste_0001.py"]
